# Generated by Django 4.0.6 on 2023-08-21 07:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_content_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('duration', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together={('user', 'subscription')},
        ),
    ]
