# Generated by Django 4.0.6 on 2023-08-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBoughtContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='channel.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payed_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
    ]
