# Generated by Django 4.0.6 on 2023-08-21 12:34

from django.db import migrations, models
import ghasedak.storage_backends.media_storage


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_userboughtcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=ghasedak.storage_backends.media_storage.MediaStorage(location='media/posts/image'), upload_to=''),
        ),
    ]
