# Generated by Django 4.0.6 on 2023-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_content_summary_alter_content_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
